version: "3.9"

volumes:
  linea-goerli:
    name: "linea-goerli"

services:
  init:
    image: ethereum/client-go:v1.11.6
    command:
    - init
    - /genesis.json
    volumes:
      - ./genesis.json:/genesis.json:ro
      - linea-goerli:/root/.ethereum

  node:
    image: ethereum/client-go:v1.11.6
    pull_policy: always
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      init:
        condition: service_completed_successfully
    command:
      --networkid=59140
      --syncmode=snap
      --http
      --http.addr='0.0.0.0'
      --http.port=8545
      --http.corsdomain='*'
      --http.api='admin,web3,eth,txpool,net'
      --http.vhosts='*'
      --bootnodes "enode://c7d29d1bbb768e73c6bd320608276dc2341670822ed1292456a7b8375de35b5348e3b6bac63783a53d697378b25c5658681683f7621e31b37c605993c5ee13bd@18.189.141.200:30303,enode://14ba040dd8c5b1ea607fabf98c3c7c398658f897c502d0ca5202dce8907e83be953995ce5c3f72def2af710c072fe38de4e9347a299370fc82d6d17819967c93@3.144.118.88:30303"
      --verbosity=3
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
    volumes:
      - ./genesis.json:/genesis.json:ro
      - linea-goerli:/root/.ethereum

  #Besu node currently not peering with bootnodes
  besu-node:
    hostname: besu-node
    container_name: besu-node
    image: consensys/linea-besu:${SEQUENCER_TAG:-linea-delivery-8}
    platform: linux/amd64
    depends_on:
      linea-besu-sequencer-plugin-downloader:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "bash -c \"[ -f /tmp/pid ]\"" ]
      interval: 1s
      timeout: 1s
      retries: 120
    restart: "no"
    environment:
      LOG4J_CONFIGURATION_FILE: /var/lib/besu/log4j.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/var/lib/besu/sequencer.config.toml \
        --bootnodes="enode://c7d29d1bbb768e73c6bd320608276dc2341670822ed1292456a7b8375de35b5348e3b6bac63783a53d697378b25c5658681683f7621e31b37c605993c5ee13bd@18.189.141.200:30303,enode://14ba040dd8c5b1ea607fabf98c3c7c398658f897c502d0ca5202dce8907e83be953995ce5c3f72def2af710c072fe38de4e9347a299370fc82d6d17819967c93@3.144.118.88:30303"
    volumes:
      - ../config/linea-besu-sequencer/sequencer.config.toml:/var/lib/besu/sequencer.config.toml:ro
      - ./genesis.json:/var/lib/besu/genesis.json:ro
      - ../config/linea-besu-sequencer/log4j.xml:/var/lib/besu/log4j.xml:ro
      - ../../tmp/linea-besu-sequencer/plugins:/opt/besu/plugins/

  linea-besu-sequencer-plugin-downloader:
    image: busybox:1.28
    command: [ "sh", "/file-downloader.sh", "https://github.com/Consensys/besu-sequencer-plugins/releases/download/v0.1.4-test2/besu-sequencer-plugins-v0.1.4-test2.jar",  "/linea-besu-sequencer" ]
    volumes:
      - ../scripts/file-downloader.sh:/file-downloader.sh:ro
      - ../../tmp/linea-besu-sequencer/plugins:/linea-besu-sequencer/
