name: Bug Report
description: Create a report to help us improve
labels: ['bug']
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here.
    validations:
      required: true
  - type: textarea
    id: issue-reproduction
    attributes:
      label: Steps to reproduce
      description: Describe steps to reproduce the behavior.
      placeholder: Steps to reproduce the bug here.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Expected behavior here.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Add screenshots here.
  - type: markdown
    attributes:
     value: |
       **Desktop (Please complete the following information, if applicable)**
  - type: checkboxes
    id: desktop-os
    attributes:
      label: What OS are you using?
      description: Select the relevant operating system.
      options:
        - label: Windows
          required: false
        - label: macOS
          required: false
        - label: Linux
          required: false
  - type: dropdown
    id: desktop-browser
    attributes:
      label: What browser(s) are you seeing the problem on?
      description: Select the relevant browser(s).
      multiple: true
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge
        - label: Brave
        - label: Other
  - type: input
    id: other-browser-desktop
    attributes:
      label: Specify other browser
      description: If you selected "Other" for the browser, please specify.
      placeholder: Specify other browser here...
    validations:
      required: false
  - type: input
    id: browser-version-desktop
    attributes:
      label: Browser version
      description: Specify the version of the browser.
      placeholder: Specify browser version here...
    validations:
        required: false
  - type: markdown
    attributes:
      value: |
        **Mobile (Please complete the following information, if applicable)**
  - type: input
    id: smartphone-device
    attributes:
      label: What device are you using?
      description: Specify the device you are using.
      placeholder: e.g. iPhone 13
    validations:
      required: false
  - type: input
    id: smartphone-os
    attributes:
      label: What OS are you using?
      description: Specify the operating system you are using.
      placeholder: e.g. iOS 17
    validations:
      required: false
  - type: input
    id: smartphone-browser
    attributes:
      label: What browsers are you seeing the problem on?
      description: Specify the browser you are using.
      placeholder: e.g. Safari
    validations:
      required: false
  - type: input
    id: browser-version-mobile
    attributes:
      label: Browser version
      description: Specify the version of the browser.
      placeholder: Specify browser version here.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Additional context here.
