version: "3.9"

volumes:
  linea-goerli:
    name: "linea-goerli"

services:
  init:
    image: ethereum/client-go:v1.13.4
    command:
    - init
    - /genesis.json
    volumes:
      - ./genesis.json:/genesis.json:ro
      - linea-goerli:/root/.ethereum

  node:
    image: ethereum/client-go:v1.13.4
    pull_policy: always
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      init:
        condition: service_completed_successfully
    command:
      --networkid=59140
      --syncmode=snap
      --http
      --http.addr='0.0.0.0'
      --http.port=8545
      --http.corsdomain='*'
      --http.api='admin,web3,eth,txpool,net'
      --http.vhosts='*'
      --bootnodes "enode://700f0d5a5f2beadc307b7b8f1a251f8b75033c8222ca65bfb1aecc4c4a0a86d6d6ef8420e780f6ace7cc3d1b837606b116109cc53b00931d3debc1346b9ccbb8@13.51.255.207:31001,enode://cbbaacaf47a005cb389b40f6676d63800cc65295aad0983e5ce9f2e5bf805274cded5ef313993a2564591d6caab6322c2a39a0b3a21143034378179c7d5ecd44@3.16.167.169:31001"
      --verbosity=3
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
    volumes:
      - ./genesis.json:/genesis.json:ro
      - linea-goerli:/root/.ethereum