version: "3.9"

volumes:
  linea-mainnet:
    name: "linea-mainnet"

services:
  init:
    image: ethereum/client-go:v1.13.4
    command:
    - init
    - /genesis.json
    volumes:
      - ./genesis.json:/genesis.json:ro
      - linea-mainnet:/root/.ethereum

  node:
    image: ethereum/client-go:v1.13.4
    pull_policy: always
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      init:
        condition: service_completed_successfully
    command:
      --networkid=59144
      --syncmode=snap
      --http
      --http.addr='0.0.0.0'
      --http.port=8545
      --http.corsdomain='*'
      --http.api='admin,web3,eth,txpool,net'
      --http.vhosts='*'
      --bootnodes=enode://ca2f06aa93728e2883ff02b0c2076329e475fe667a48035b4f77711ea41a73cf6cb2ff232804c49538ad77794185d83295b57ddd2be79eefc50a9dd5c48bbb2e@3.23.106.165:30303,enode://eef91d714494a1ceb6e06e5ce96fe5d7d25d3701b2d2e68c042b33d5fa0e4bf134116e06947b3f40b0f22db08f104504dd2e5c790d8bcbb6bfb1b7f4f85313ec@3.133.179.213:30303,enode://cfd472842582c422c7c98b0f2d04c6bf21d1afb2c767f72b032f7ea89c03a7abdaf4855b7cb2dc9ae7509836064ba8d817572cf7421ba106ac87857836fa1d1b@3.145.12.13:30303
      --verbosity=3
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
    volumes:
      - ./genesis.json:/genesis.json:ro
      - linea-mainnet:/root/.ethereum
