---
  name: Nightly check
  
  on:
    schedule:
      - cron: "0 0 * * *"
    workflow_dispatch: {}
  
  jobs:
    linkCheck:
      name: Run link check
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: LinkCheck mdx files
          uses: ConsenSys/docs-gha/linkcheck@main
          with:
              FILE_EXTENSION: mdx
              MODIFIED_FILES_ONLY: no
          continue-on-error: true
        - name: LinkCheck md files
          uses: ConsenSys/docs-gha/linkcheck@main
          with:
              FILE_EXTENSION: md
              MODIFIED_FILES_ONLY: no